[project]
name = "tennisbooking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=43.0.3",
    "selenium>=4.26.1",
    "tqdm>=4.67.0",
]
